name: Update Dependencies
on:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         * * * * *
    - cron: "0 4 * * 3" # 4am every Wednesday
jobs:
  update-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - run: gradle wrapper --write-locks
      - run: ./gradlew --version
      - run: ./gradlew dependencies --write-locks

      - uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: Update Java Dependencies"
          branch: topic/update-java
          token: ${{ secrets.PAT }}
      - run: gh pr merge --auto --squash ${{ env.PULL_REQUEST_NUMBER }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
  update-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
      - run: corepack enable
      - run: yarn set version stable
      - run: yarn up
      - run: yarn up -R
      - run: yarn dedupe
      - uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: Update Node Dependencies"
          branch: topic/update-node
          token: ${{ secrets.PAT }}
      - run: gh pr merge --auto --squash ${{ env.PULL_REQUEST_NUMBER }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
